# Generated by Django 3.1.3 on 2022-02-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='post_office',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='village',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
