# Generated by Django 3.1.3 on 2022-02-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20220222_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='post_office',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='member',
            name='village',
            field=models.CharField(default='', max_length=63),
        ),
    ]
