# Generated by Django 3.1.3 on 2022-03-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_passwordresetrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='done',
        ),
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='new_password',
        ),
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='username',
        ),
    ]
