# Generated by Django 3.1.3 on 2022-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20220329_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='new_password',
            field=models.CharField(default='asdf', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='phone',
            field=models.CharField(default='asdf', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='username',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
    ]
