# Generated by Django 3.1.3 on 2021-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20210323_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='year',
            field=models.CharField(default=2021, max_length=10),
        ),
    ]
