# Generated by Django 3.1.3 on 2022-03-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20220329_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetrequest',
            old_name='username',
            new_name='passport',
        ),
    ]
