# Generated by Django 3.1.3 on 2021-03-24 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20210323_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='src.member'),
        ),
    ]
