# Generated by Django 3.1.3 on 2022-03-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_educationalinstitute_mosque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitute',
            name='stablished_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='stablished_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
