# Generated by Django 3.1.3 on 2022-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20220330_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitute',
            name='headmaster',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationalinstitute',
            name='school_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='imam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
