# Generated by Django 3.1.3 on 2021-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_auto_20211003_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='city',
            new_name='upazilla',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='current_address',
            new_name='zilla',
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('g', 'General Member'), ('l', 'Lifetime Member'), ('f', 'Founding Member'), ('a', 'Admin')], default='', max_length=24),
        ),
    ]
