# Generated by Django 3.1.3 on 2021-11-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_auto_20211103_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
