# Generated by Django 3.1.3 on 2021-11-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_remove_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('facebook', models.URLField(default='')),
                ('linkedin', models.URLField(default='')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
