# Generated by Django 3.1.3 on 2021-11-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_advisorycouncil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvisoryCouncil',
            new_name='AdvisoryMember',
        ),
    ]
