# Generated by Django 3.1.3 on 2021-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_auto_20211128_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorymember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advisory_members/'),
        ),
    ]
