# Generated by Django 3.1.3 on 2021-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_advisorymember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorymember',
            name='image',
            field=models.ImageField(upload_to='advisory_members/'),
        ),
    ]
