# Generated by Django 3.1.3 on 2021-11-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_auto_20211128_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorymember',
            name='facebook',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='advisorymember',
            name='linkedin',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
