# Generated by Django 3.1.3 on 2021-12-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_auto_20211201_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationscholarship',
            name='monthly_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='educationscholarship',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='educationscholarship',
            name='yearly_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicalassistance',
            name='bedget',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicalassistance',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='medicalassistance',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingassistance',
            name='classes',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingassistance',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trainingassistance',
            name='total_trainee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
