# Generated by Django 3.1.3 on 2021-12-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='caption',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='name',
            new_name='title',
        ),
    ]
