# Generated by Django 3.1.3 on 2021-12-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_auto_20211203_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
