# Generated by Django 3.1.3 on 2021-12-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_auto_20211209_1714'),
        ('src', '0028_downloadpolicy'),
    ]

    operations = [
    ]
