# Generated by Django 3.1.3 on 2021-12-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_merge_20211209_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadpolicy',
            options={'verbose_name_plural': 'Download Policies'},
        ),
    ]
