# Generated by Django 3.1.3 on 2022-01-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('src', '0030_auto_20211210_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='election_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='year',
            field=models.CharField(default=2022, max_length=10),
        ),
    ]
