# Generated by Django 3.1.3 on 2022-01-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0032_auto_20220116_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comission',
            new_name='Commission',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='comission_member',
            new_name='commission_member',
        ),
    ]
