# Generated by Django 3.1.3 on 2022-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0033_auto_20220116_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='commission_member',
        ),
        migrations.AddField(
            model_name='member',
            name='commission_member',
            field=models.ManyToManyField(blank=True, to='src.Commission'),
        ),
    ]
