# Generated by Django 3.1.3 on 2022-01-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0034_auto_20220116_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='commission_member',
        ),
        migrations.AddField(
            model_name='member',
            name='election_commission_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.commission'),
        ),
    ]
