# Generated by Django 3.1.3 on 2022-01-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0035_auto_20220116_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='election_commission_member',
        ),
        migrations.AddField(
            model_name='member',
            name='election_commission',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
