# Generated by Django 3.1.3 on 2022-01-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0036_auto_20220116_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='election_commission',
        ),
    ]
